
// This file is generated by Timber Generator
// Name: bundle/swift/timber/Sources/timber/luopan.swift
// Version: 0.5.1
// Time: 2021/10/5
// Parser: v1.3.1 @Tue Sep 28 2021 08:00:00 GMT+0800 (中国标准时间)


public struct LuopanLayerDefinition {
  public let elements: ElementSequenceProtocol
  public let start: Double
  public let distance: Double
  public let width: Double
  public let order: Int
  public init(_ elements: ElementSequenceProtocol, _ start: Double, _ distance: Double, _ width: Double, _ order: Int) {
    self.elements = elements
    self.start = start
    self.distance = distance
    self.width = width
    self.order = order
  }
}

public typealias LuopanDefinitions = [LuopanLayerName: LuopanLayerDefinition]

public let luopanDefinitions: LuopanDefinitions = [
  .XTBG:        LuopanLayerDefinition(Sequences.xtbg,       22.5, 45, 4,  10),
  .HTLSS:       LuopanLayerDefinition(Sequences.htlss,      22.5, 45, 3,  20),
  .HTBG:        LuopanLayerDefinition(Sequences.htbg,       22.5, 45, 6,  30),
  .TD60LONG:    LuopanLayerDefinition(Sequences.td60long,   1.5,  6,  7,  40),
  .DPZZ:        LuopanLayerDefinition(Sequences.shan24,     7.5,  15, 10, 50),
  .DPZZ120FJ:   LuopanLayerDefinition(Sequences.dpzz120fj,  1.5,  3,  7,  60),
  .CS72LONG:    LuopanLayerDefinition(Sequences.cs72long,   2.5,  5,  7,  70),
  .SH24JS:      LuopanLayerDefinition(Sequences.sh24js,     7.5,  15, 10, 80),
  .BSHQ:        LuopanLayerDefinition(Sequences.bshq,       22.5, 45, 10, 90),
  .RPZZ:        LuopanLayerDefinition(Sequences.shan24,     0,    15, 10, 300),
  .TPFZ:        LuopanLayerDefinition(Sequences.shan24,     15,   15, 10, 400),
]

public func roll(_ alpha: Double) -> [LuopanLayerName: LiteralType] {
  var result: [LuopanLayerName: LiteralType] = [:]
  for (name, def) in luopanDefinitions {
    let vals = def.elements.literals
    if def.start >= alpha {
      result[name] = vals[vals.count - 1]
    } else {
      for i in 0...vals.count-1 {
        if Double(i+1)*def.distance + def.start >= alpha {
          result[name] = vals[i]
          break
        }
      }
    }
  }
  return result
}


